Add director
84R5/java-filmorate pull request #23
Opened 2023-04-13 18:13 UTC by ReTeRWert

2023-04-13 19:02 UTC, MR-k0f31n reviewed
Старшие коллеги конечно еще посмотрят. я только к аннотации валидации в директоре имею вопрос

2023-04-13 19:02 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Film> getDirectorFilms(Long directorId, String sortBy) {
как по мне не очевидное название getFilmsByDirector лучше

2023-04-13 19:02 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    @NotBlank
Бланк разве не проверяет на налл? у меня работало

2023-04-13 19:17 UTC, ReTeRWert commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +                .collect(Collectors.toList());
я собственно где то в своем коде так и делал, но тут я только сделал чтобы смотрелось получше)

2023-04-14 07:29 UTC, mvinogradovHub requested changes

2023-04-14 07:29 UTC, mvinogradovHub commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorDbStorage.java
> +            throw new NotFoundException("Режиссер с идентификатором: " + id + " не существует.");
Все же я против генерировать исключения в хранилище. А если хранилище заменить другим? Что тогда будет? Тут надо просто вернуть null, а в сервисе обработать его, вызвав исключение

2023-04-14 08:05 UTC, MR-k0f31n commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                .directors(directorStorage.findDirectorsByFilm(rs.getLong("film_id")))
Вот для этого предлагаю при джоинить сразу режесеров, 99% что застрелят нас в упор с ракетницы

2023-04-14 14:47 UTC, mvinogradovHub approved these changes

2023-04-14 18:44 UTC, Siberian797 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +@RequiredArgsConstructor
Лайк

2023-04-14 18:56 UTC, Siberian797 commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorStorage.java
> +    Director getDirector(Long id);
Действительно лучше сделать getDirectorById

2023-04-14 18:56 UTC, Siberian797 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> getDirectorFilms(@PathVariable Long directorId,
Думаю, лучше будет getFilmsByDirectorId

2023-04-14 18:56 UTC, Siberian797 commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorDbStorage.java
> +    public Director getDirector(Long id) {
getDirectorById

2023-04-14 18:56 UTC, Siberian797 commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    @NotNull
@NotBlank включает в себя @NotNull

2023-04-14 19:28 UTC, merged